### ISSUE TITLE
CKEditor build fails with `strictNullChecks: false` in TypeScript

### ISSUE THREAD

**Issue by bnf** [ckeditor/ckeditor5#20238]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@ckeditor/ckeditor5-utils@48.5.1` for [TYPO3](https://review.typo3.org/c/Packages/TYPO3.CMS/+/94113/13/Build/patches/@ckeditor%252Bckeditor5-utils%252B48.5.1.patch).

We do not use strict TypeScript types yet and therefore all builds fail when upgrading to CKEditor v48 (caused by https://github.com/ckeditor/ckeditor5/commit/e6530c1) because the mixins base classes are considered as possibly undefined.

<details>
<summary>Expand to see build log here</summary>

```        node_modules/@ckeditor/ckeditor5-core/dist/command.d.ts:24:38 - error TS2507: Type 'undefined' is not a constructor function type.

        24 export declare class Command extends CommandBase {
                                                ~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-core/dist/command.d.ts:193:56 - error TS2344: Type 'Command' does not satisfy the constraint 'Observable & { execute: (...args: any[]) => any; }'.
          Type 'Command' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        193 export type CommandExecuteEvent = DecoratedMethodEvent<Command, "execute">;
                                                                   ~~~~~~~

        node_modules/@ckeditor/ckeditor5-core/dist/contextplugin.d.ts:29:44 - error TS2507: Type 'undefined' is not a constructor function type.

        29 export declare class ContextPlugin extends ContextPluginBase implements PluginInterface {
                                                      ~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-core/dist/editor/editor.d.ts:39:46 - error TS2507: Type 'undefined' is not a constructor function type.

        39 export declare abstract class Editor extends EditorBase {
                                                        ~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-core/dist/plugin.d.ts:14:37 - error TS2507: Type 'undefined' is not a constructor function type.

        14 export declare class Plugin extends PluginBase implements PluginInterface {
                                               ~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-core/dist/plugincollection.d.ts:14:72 - error TS2507: Type 'undefined' is not a constructor function type.

        14 export declare class PluginCollection<TContext extends object> extends PluginCollectionBase implements Iterable<PluginEntry<TContext>> {
                                                                                  ~~~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/controller/datacontroller.d.ts:42:45 - error TS2507: Type 'undefined' is not a constructor function type.

        42 export declare class DataController extends DataControllerBase {
                                                       ~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/controller/editingcontroller.d.ts:22:48 - error TS2507: Type 'undefined' is not a constructor function type.

        22 export declare class EditingController extends EditingControllerBase {
                                                          ~~~~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/conversion/downcastdispatcher.d.ts:114:49 - error TS2507: Type 'undefined' is not a constructor function type.

        114 export declare class DowncastDispatcher extends DowncastDispatcherBase {
                                                            ~~~~~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/conversion/mapper.d.ts:39:37 - error TS2507: Type 'undefined' is not a constructor function type.

        39 export declare class Mapper extends MapperBase {
                                               ~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/conversion/mapper.d.ts:415:42 - error TS2507: Type 'undefined' is not a constructor function type.

        415 export declare class MapperCache extends MapperCacheBase {
                                                     ~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/conversion/upcastdispatcher.d.ts:118:47 - error TS2507: Type 'undefined' is not a constructor function type.

        118 export declare class UpcastDispatcher extends UpcastDispatcherBase {
                                                          ~~~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/model/document.d.ts:34:44 - error TS2507: Type 'undefined' is not a constructor function type.

        34 export declare class ModelDocument extends ModelDocumentBase {
                                                      ~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/model/markercollection.d.ts:29:47 - error TS2507: Type 'undefined' is not a constructor function type.

        29 export declare class MarkerCollection extends MarkerCollectionBase implements Iterable<Marker> {
                                                         ~~~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/model/model.d.ts:29:36 - error TS2507: Type 'undefined' is not a constructor function type.

        29 export declare class Model extends ModelBase {
                                              ~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/model/model.d.ts:827:61 - error TS2344: Type 'Model' does not satisfy the constraint 'Observable & { applyOperation: (...args: any[]) => any; }'.
          Type 'Model' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        827 export type ModelApplyOperationEvent = DecoratedMethodEvent<Model, "applyOperation">;
                                                                        ~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/model/model.d.ts:874:60 - error TS2344: Type 'Model' does not satisfy the constraint 'Observable & { deleteContent: (...args: any[]) => any; }'.
          Type 'Model' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        874 export type ModelDeleteContentEvent = DecoratedMethodEvent<Model, "deleteContent">;
                                                                       ~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/model/model.d.ts:884:62 - error TS2344: Type 'Model' does not satisfy the constraint 'Observable & { modifySelection: (...args: any[]) => any; }'.
          Type 'Model' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        884 export type ModelModifySelectionEvent = DecoratedMethodEvent<Model, "modifySelection">;
                                                                         ~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/model/model.d.ts:894:65 - error TS2344: Type 'Model' does not satisfy the constraint 'Observable & { getSelectedContent: (...args: any[]) => any; }'.
          Type 'Model' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        894 export type ModelGetSelectedContentEvent = DecoratedMethodEvent<Model, "getSelectedContent">;
                                                                            ~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/model/schema.d.ts:32:42 - error TS2507: Type 'undefined' is not a constructor function type.

        32 export declare class ModelSchema extends ModelSchemaBase {
                                                    ~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/view/document.d.ts:19:43 - error TS2507: Type 'undefined' is not a constructor function type.

        19 export declare class ViewDocument extends ViewDocumentBase {
                                                     ~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/view/observer/domeventobserver.d.ts:80:11 - error TS4113: This member cannot have an 'override' modifier because it is not declared in the base class 'Observer'.

        80  override fire(eventType: string | EventInfo, domEvent: Event, additionalData?: AdditionalData): void;
                     ~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/view/observer/observer.d.ts:18:48 - error TS2507: Type 'undefined' is not a constructor function type.

        18 export declare abstract class Observer extends ObserverBase {
                                                          ~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/view/renderer.d.ts:26:43 - error TS2507: Type 'undefined' is not a constructor function type.

        26 export declare class ViewRenderer extends ViewRendererBase {
                                                     ~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-engine/dist/view/view.d.ts:65:42 - error TS2507: Type 'undefined' is not a constructor function type.

        65 export declare class EditingView extends EditingViewBase {
                                                    ~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-link/dist/utils/manualdecorator.d.ts:17:50 - error TS2507: Type 'undefined' is not a constructor function type.

        17 export declare class LinkManualDecorator extends LinkManualDecoratorBase {
                                                            ~~~~~~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-typing/dist/textwatcher.d.ts:18:42 - error TS2507: Type 'undefined' is not a constructor function type.

        18 export declare class TextWatcher extends TextWatcherBase {
                                                    ~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/badge/badge.d.ts:18:45 - error TS2507: Type 'undefined' is not a constructor function type.

        18 export declare abstract class Badge extends BadgeBase {
                                                       ~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/colorselector/documentcolorcollection.d.ts:10:71 - error TS2344: Type 'typeof Collection<ColorDefinition>' does not satisfy the constraint 'Constructor<Emitter>'.
          Type 'Collection<ColorDefinition>' is missing the following properties from type 'Emitter': on, once, off, listenTo, and 4 more.

        10 declare const DocumentColorCollectionBase: ObservableMixinConstructor<typeof Collection<ColorDefinition>>;
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/colorselector/documentcolorcollection.d.ts:34:11 - error TS4113: This member cannot have an 'override' modifier because it is not declared in the base class 'Observable'.

        34  override add(item: ColorDefinition, index?: number): this;
                     ~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/dialog/dialogview.d.ts:265:58 - error TS2344: Type 'DialogView' does not satisfy the constraint 'Observable & { moveTo: (...args: any[]) => any; }'.
          Type 'DialogView' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        265 export type DialogViewMoveToEvent = DecoratedMethodEvent<DialogView, "moveTo">;
                                                                     ~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/editorui/editorui.d.ts:22:48 - error TS2507: Type 'undefined' is not a constructor function type.

        22 export declare abstract class EditorUI extends EditorUIBase {
                                                          ~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/focuscycler.d.ts:64:42 - error TS2507: Type 'undefined' is not a constructor function type.

        64 export declare class FocusCycler extends FocusCyclerBase {
                                                    ~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/model.d.ts:13:38 - error TS2507: Type 'undefined' is not a constructor function type.

        13 export declare class UIModel extends UIModelBase {
                                                ~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/panel/balloon/contextualballoon.d.ts:210:77 - error TS2344: Type 'ContextualBalloon' does not satisfy the constraint 'Observable & { getPositionOptions: (...args: any[]) => any; }'.
          Type 'ContextualBalloon' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        210 export type ContextualBalloonGetPositionOptionsEvent = DecoratedMethodEvent<ContextualBalloon, "getPositionOptions">;
                                                                                        ~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/template.d.ts:50:39 - error TS2507: Type 'undefined' is not a constructor function type.

        50 export declare class Template extends TemplateBase {
                                                 ~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/template.d.ts:225:18 - error TS4112: This member cannot have an 'override' modifier because its containing class 'Template' does not extend another class.

        225  static override bind<TObservable extends Observable>(observable: TObservable, emitter: Emitter): BindChain<TObservable>;
                             ~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/tooltipmanager.d.ts:75:45 - error TS2507: Type 'undefined' is not a constructor function type.

        75 export declare class TooltipManager extends TooltipManagerBase {
                                                       ~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/view.d.ts:82:79 - error TS2507: Type 'undefined' is not a constructor function type.

        82 export declare class View<TElement extends HTMLElement = HTMLElement> extends ViewBase {
                                                                                         ~~~~~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/view.d.ts:389:54 - error TS2344: Type 'View<HTMLElement>' does not satisfy the constraint 'Observable & { render: (...args: any[]) => any; }'.
          Type 'View<HTMLElement>' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        389 export type UIViewRenderEvent = DecoratedMethodEvent<View, "render">;
                                                                 ~~~~

        node_modules/@ckeditor/ckeditor5-ui/dist/viewcollection.d.ts:113:11 - error TS4113: This member cannot have an 'override' modifier because it is not declared in the base class 'Collection<TView>'.

        113  override delegate(...events: Array<string>): EmitterMixinDelegateChain;
                      ~~~~~~~~

        node_modules/@ckeditor/ckeditor5-upload/dist/filereader.d.ts:13:41 - error TS2507: Type 'undefined' is not a constructor function type.

        13 export declare class FileReader extends FileReaderBase {
                                                   ~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-upload/dist/filerepository.d.ts:119:34 - error TS2507: Type 'undefined' is not a constructor function type.

        119 declare class FileLoader extends FileLoaderBase {
                                             ~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-utils/dist/collection.d.ts:22:72 - error TS2507: Type 'undefined' is not a constructor function type.

        22 export declare class Collection<T extends Record<string, any>> extends CollectionBase implements Iterable<T> {
                                                                                  ~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-utils/dist/focustracker.d.ts:25:43 - error TS2507: Type 'undefined' is not a constructor function type.

        25 export declare class FocusTracker extends FocusTrackerBase {
                                                     ~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-widget/dist/highlightstack.d.ts:22:51 - error TS2507: Type 'undefined' is not a constructor function type.

        22 export declare class WidgetHighlightStack extends WidgetHighlightStackBase {
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-widget/dist/widgetresize/resizer.d.ts:12:44 - error TS2507: Type 'undefined' is not a constructor function type.

        12 export declare class WidgetResizer extends WidgetResizerBase {
                                                      ~~~~~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-widget/dist/widgetresize/resizer.d.ts:161:60 - error TS2344: Type 'WidgetResizer' does not satisfy the constraint 'Observable & { begin: (...args: any[]) => any; }'.
          Type 'WidgetResizer' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        161 export type WidgetResizerBeginEvent = DecoratedMethodEvent<WidgetResizer, "begin">;
                                                                       ~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-widget/dist/widgetresize/resizer.d.ts:165:61 - error TS2344: Type 'WidgetResizer' does not satisfy the constraint 'Observable & { cancel: (...args: any[]) => any; }'.
          Type 'WidgetResizer' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        165 export type WidgetResizerCancelEvent = DecoratedMethodEvent<WidgetResizer, "cancel">;
                                                                        ~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-widget/dist/widgetresize/resizer.d.ts:169:61 - error TS2344: Type 'WidgetResizer' does not satisfy the constraint 'Observable & { commit: (...args: any[]) => any; }'.
          Type 'WidgetResizer' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        169 export type WidgetResizerCommitEvent = DecoratedMethodEvent<WidgetResizer, "commit">;
                                                                        ~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-widget/dist/widgetresize/resizer.d.ts:173:65 - error TS2344: Type 'WidgetResizer' does not satisfy the constraint 'Observable & { updateSize: (...args: any[]) => any; }'.
          Type 'WidgetResizer' is missing the following properties from type 'Observable': set, bind, unbind, decorate, and 8 more.

        173 export type WidgetResizerUpdateSizeEvent = DecoratedMethodEvent<WidgetResizer, "updateSize">;
                                                                            ~~~~~~~~~~~~~

        node_modules/@ckeditor/ckeditor5-widget/dist/widgetresize/resizerstate.d.ts:14:48 - error TS2507: Type 'undefined' is not a constructor function type.

        14 export declare class WidgetResizeState extends WidgetResizeStateBase {
```
</details>

Here is the diff that solved my problem by swapping the conditions to check for `undefined` explicitly instead of checking for the base implementation (which is also considered possibly-undefined in with `strictNullChecks: false` in TypeScript).

Any chance that you could ship this fix in the next release? We understand that we should migrate to strict types, but I guess other projects could be affected as well.

```diff
diff --git a/node_modules/@ckeditor/ckeditor5-utils/dist/dom/emittermixin.d.ts b/node_modules/@ckeditor/ckeditor5-utils/dist/dom/emittermixin.d.ts
index caf9542..5b34b9e 100644
--- a/node_modules/@ckeditor/ckeditor5-utils/dist/dom/emittermixin.d.ts
+++ b/node_modules/@ckeditor/ckeditor5-utils/dist/dom/emittermixin.d.ts
@@ -17,10 +17,10 @@ import type { Constructor, Mixed } from "../mix.js";
 * class MyDomEmitter extends MyDomEmitterBase {}
 * ```
 */
-export type DomEmitterMixinConstructor<Base extends Constructor<Emitter> | undefined = undefined> = Base extends Constructor<Emitter> ? Mixed<Base, DomEmitter> : {
+export type DomEmitterMixinConstructor<Base extends Constructor<Emitter> | undefined = undefined> = Base extends undefined ? {
 	new (): DomEmitter;
 	prototype: DomEmitter;
-};
+} : Mixed<Base, DomEmitter>;
 /**
 * Mixin that injects the DOM events API into its host. It provides the API
 * compatible with {@link module:utils/emittermixin~Emitter}.
diff --git a/node_modules/@ckeditor/ckeditor5-utils/dist/emittermixin.d.ts b/node_modules/@ckeditor/ckeditor5-utils/dist/emittermixin.d.ts
index b175cd7..e52fb21 100644
--- a/node_modules/@ckeditor/ckeditor5-utils/dist/emittermixin.d.ts
+++ b/node_modules/@ckeditor/ckeditor5-utils/dist/emittermixin.d.ts
@@ -18,10 +18,10 @@ import "./version.js";
 * class MyEmitter extends MyEmitterBase {}
 * ```
 */
-export type EmitterMixinConstructor<Base extends Constructor | undefined = undefined> = Base extends Constructor ? Mixed<Base, Emitter> : {
+export type EmitterMixinConstructor<Base extends Constructor | undefined = undefined> = Base extends undefined ? {
 	new (): Emitter;
 	prototype: Emitter;
-};
+} : Mixed<Base, Emitter>;
 /**
 * Mixin that injects the {@link ~Emitter events API} into its host.
 *
diff --git a/node_modules/@ckeditor/ckeditor5-utils/dist/observablemixin.d.ts b/node_modules/@ckeditor/ckeditor5-utils/dist/observablemixin.d.ts
index 848550c..e40f881 100644
--- a/node_modules/@ckeditor/ckeditor5-utils/dist/observablemixin.d.ts
+++ b/node_modules/@ckeditor/ckeditor5-utils/dist/observablemixin.d.ts
@@ -16,10 +16,10 @@ import type { Constructor, Mixed } from "./mix.js";
 * class MyObservable extends MyObservableBase {}
 * ```
 */
-export type ObservableMixinConstructor<Base extends Constructor<Emitter> | undefined = undefined> = Base extends Constructor<Emitter> ? Mixed<Base, Observable> : {
+export type ObservableMixinConstructor<Base extends Constructor<Emitter> | undefined = undefined> = Base extends undefined ? {
 	new (): Observable;
 	prototype: Observable;
-};
+} : Mixed<Base, Observable>;
 /**
 * A mixin that injects the "observable properties" and data binding functionality described in the
 * {@link ~Observable} interface.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Thanks, Benjamin

**Comment by pomek** [comment]
Hi @bnf, thanks for the detailed report – and especially for tracking it down to the exact type aliases. That saved us a lot of time.

You are right, and this is a real regression on our side. We introduced it when we enabled `isolatedDeclarations`. With `strictNullChecks` disabled, `undefined` is assignable to `Constructor`, so the default `Base = undefined` takes the wrong branch of the conditional type and the whole alias collapses to `undefined`. Everything else in your build log follows from that.

We plan to fix it. The shape will be close to your patch, with one adjustment: we also need `Extract<Base, Constructor>` in the `false` branch, because our own sources compile with strict, and TypeScript does not narrow the type parameter there.

We will update this issue once the fix is scheduled for a release.

**Comment by pomek** [comment]
Fixed by 9875dcbda468d4f9554eec4404d5b867f6899288. Unfortunately, I can't say when it will be available on npm. I will get back to you tomorrow.

**Comment by pomek** [comment]
@bnf, we plan to release a fix for it next Tuesday, 22.09.

**Comment by pomek** [comment]
The **v48.5.2** version is available. See https://github.com/ckeditor/ckeditor5/releases/tag/v48.5.2.
