### ISSUE TITLE
Inserting a math formula crashes the editor

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#7885]
## 📝 Provide detailed reproduction steps (if any)

1.  Insert a math formula.

### ✔️ Expected result

The formula is inserted.

### ❌ Actual result

The editor crashes.

## 📃 Other details

CKE5 version: Latest master

**Error**

```
plugin.js:374 Uncaught TypeError: viewWriter.createContainerElement is not a function
    at createViewWidget (plugin.js:374)
    at DowncastDispatcher.<anonymous> (downcasthelpers.js:788)
    at DowncastDispatcher.fire (emittermixin.js:209)
    at DowncastDispatcher._testAndFire (downcastdispatcher.js:473)
    at DowncastDispatcher.convertInsert (downcastdispatcher.js:184)
    at DowncastDispatcher.convertChanges (downcastdispatcher.js:136)
    at editingcontroller.js:94
    at View.change (view.js:479)
    at Document.EditingController.listenTo.priority (editingcontroller.js:93)
    at Document.fire (emittermixin.js:209)
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
Here's the first bad commit - 9a4d526.

**Comment by mlewand** [comment]
Reason for this is that MathType team has to update the plugin after our BC introduced in v22.0.0.

**Comment by Reinmar** [comment]
What's the status of this ticket?
