### ISSUE TITLE
Using a React component in a block widget demo does not work

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#5850]
## 📝 Provide a description of requested docs changes

Using a React component in a block widget does demo not work

I've tried to click Products in the demo

```
CKEditorError: "renderProduct is not a function"
    reactWrapper using-react-in-widget.js:125
    viewToDom domconverter.js:218
    viewChildrenToDom domconverter.js:272
    viewToDom domconverter.js:244
    viewChildrenToDom domconverter.js:272
    _updateChildren renderer.js:535
    render renderer.js:203
    _render view.js:682
    View view.js:187
    fire emittermixin.js:209
    change view.js:479
    _disableRendering view.js:669
    EditingController editingcontroller.js:84
    fire emittermixin.js:209
    _runPendingChanges model.js:793
    enqueueChange model.js:226
    init datacontroller.js:268
    decorate observablemixin.js:255
    fire emittermixin.js:209
    methodName observablemixin.js:259
    create classiceditor.js:212
ckeditor.js:5:3660
```

```
TypeError: _this6.editor is null6 using-react-in-a-widget.html line 61637 > scriptElement:242:6
    onClick using-react-in-a-widget.html line 61637 > scriptElement:242
    onClick using-react-in-a-widget.html line 61637 > scriptElement:43
    React 17
    bind_applyFunctionN self-hosted:1197
    dispatchEvent self-hosted:1161
    unstable_runWithPriority scheduler.development.js:697
    React 4
    dispatchDiscreteEvent self-hosted:1120
```

**Comment by mlewand** [comment]
Caused by 9c957a75ab9ac3b1865d02af78b75f3e77f3e982 - interestingly it should work, but there's a bug in our config getter (or rather in lodash's `cloneDeepWith` as I didn't check it deelply). I have reverted the mentioned change.

**Comment by Reinmar** [comment]
Did it fix https://github.com/ckeditor/ckeditor5/issues/5850 too?

Also, this change was done because right now the documentation is inconsistent. In one place we do:

```js
editor.config.get( 'products.productRenderer' );
```

And in the other place we do:

```js
editor.config.get( 'products' ).productRenderer;
```

![image](https://user-images.githubusercontent.com/156149/70130580-152bb680-1681-11ea-98f1-13a053db5aa7.png)

Please open a ticket for it29 to fix that because this was actually reported by the community that it's confusing.
